url: https://www.pythonfrederick.org
baseurl: ""

# Site settings
title: Python Frederick
email: python-frederick-list@meetup.com
description: >-
  Python Frederick is a Python User Group located in Frederick, MD.
  We aim to grow the technology community in the NW Washington, DC area
  for a better understanding of the Python programming language
  and its ecosystem.

# Team names, titles and social links
people:
- name: Chris Malone
  pic: 3
  position: Co-Organizer
  social:
    - title: facebook
      url: https://www.facebook.com/Christopher.G.Malone
    - title: meetup
      url: https://www.meetup.com/python-frederick/members/206255812/

- name: Christine Lee
  pic: 5
  position: Co-Organizer
  social:
    - title: meetup
      url: https://www.meetup.com/python-frederick/members/182962638/

- name: Lugene
  pic: 4
  position: Co-Organizer Emeritus
  social:
    - title: meetup
      url: https://www.meetup.com/python-frederick/members/3763715/

- name: Matt Layman
  pic: 1
  position: Lead Organizer
  social:
    - title: twitter
      url: https://twitter.com/mblayman
    - title: facebook
      url: https://www.facebook.com/matthewlayman
    - title: meetup
      url: https://www.meetup.com/python-frederick/members/187877491/

- name: Patrick Pierson
  pic: 2
  position: Co-Organizer
  social:
    - title: twitter
      url: https://twitter.com/pierson_pat
    - title: facebook
      url: https://www.facebook.com/ihasn
    - title: meetup
      url: https://www.meetup.com/python-frederick/members/171706482/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pythonfrederick
  - title: github
    url: https://github.com/python-frederick
  - title: facebook
    url: https://www.facebook.com/PythonFrederick/
  - title: meetup
    url: https://www.meetup.com/python-frederick/
  - title: slack
    url: https://fredericktechinvite.herokuapp.com/

# Postal address (add as many lines as necessary)
address:
  - line: #3481 Melrose Place
  - line: #Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
